# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180417_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='\u670d\u52a1\u5730\u5740')),
                ('ports', models.CharField(max_length=500, verbose_name='\u4f7f\u7528\u7aef\u53e3')),
                ('contact', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u4eba')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name='\u6240\u5c5e\u4e3b\u673a')),
            ],
            options={
                'verbose_name_plural': '\u670d\u52a1',
            },
        ),
    ]
