# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='\u6536\u96c6\u7684\u8d44\u6e90\u6570\u636e')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'get_latest_by': 'created_time',
                'verbose_name_plural': '\u8d44\u6e90\u72b6\u6001',
            },
        ),
    ]
