# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_resourcestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='\u4e3b\u673a\u7ec4\u540d'),
        ),
    ]
